[tool.black]
line-length = 79
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # black-default
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.bandit]
exclude = [
   "tests/*",
   "test_*",
   "*/tests/*",
   "*/test_*"
]

exclude_dirs = [
   "mitiq/interface/mitiq_pyquil/tests"
]