name: buildtest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          make install requirements

      - name: Check types with mypy
        run: make check-types

      - name: Lint with flake8
        run: make check-style

      - name: Check code style with Black
        run: make check-format

      - name: Check code security with Bandit
        run: |
          make bandit
          make bandit-results
